### ISSUE TITLE
Training with custom dataset

### ISSUE THREAD

**Issue by ghost** [ad-freiburg/tokenization-repair#3]
First of all, thank you for your incredible work.

I would like to train the models in this paper with a custom dataset in Vietnamese. Can you please explain the data format i need to prepare, as well as some step by step instruction?

Thank you.

**Comment by hertelm** [comment]
Thanks for your interest in the project!

The readme now includes a description on how to train and use custom models.

Follow the step-by-step installation guide and make sure you change the base image in the Dockerfile to tensorflow/tensorflow:1.12.0-gpu-py3 in order to have GPU support. Then follow these steps: https://github.com/ad-freiburg/tokenization-repair#custom-models

The training data is a text file with one example sequence per line (e.g. a paragraph of text in each line). The spaces in the training data must be correct. If you need the models to be robust against OCR or spelling errors, the training data should contain such errors (but no space errors).
